name: tareas
description: An app for dividing tasks in clubs

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.7.0
  cupertino_icons: ^0.1.2
  flutter_i18n: ^0.8.3
  flutter_auth0: ^0.5.0
  flutter_webview_plugin: ^0.3.11
  shared_preferences: any
  scoped_model: ^1.0.1
  intl: ^0.16.1
  flutter_stetho: ^0.5.2
  flutter_calendar_carousel: ^1.4.12
  table_calendar: ^2.2.3
  fluttertoast: ^7.0.4
  scrollable_positioned_list: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/opensans_extra_bold.ttf
          weight: 900
        - asset: assets/fonts/opensans/opensans_bold.ttf
          weight: 700
        - asset: assets/fonts/opensans/opensans_semi_bold.ttf
          weight: 500
        - asset: assets/fonts/opensans/opensans_regular.ttf
          weight: 400
        - asset: assets/fonts/opensans/opensans_light.ttf
          weight: 300

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
